### ISSUE TITLE
Oppdatere tjenesten til å støtte abstrakt modelElement klasse og modelProperty

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-model-publisher#11]
Legger til støtte for instansiering av modelElement og modelProperty subklasser i FDK-model-publisher.

**Comment by shenluna** [comment]
Verifisert i demo. modelElement og modelProperty er abstrakte klasser som ikke brukes direkte
![image](https://user-images.githubusercontent.com/73637969/105034626-09a07800-5a5a-11eb-9096-dcdcab1d8adf.png)
