### ISSUE TITLE
Høyt antall feilmeldinger i alle miljø (fdk-model-publisher)

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#51]
Det er fire feilmeldinger som fanges opp i GCP, spesielt et høyt antall knyttet til fetcher.py
`fdk-model-publisher
"Traceback (most recent call last):
  File "/app/src/fdk_model_publisher/service/fetcher.py", line 61, in fetch
    model.title = await openapi.get("title")
TypeError: object str can't be used in 'await' expression"`

![image](https://user-images.githubusercontent.com/8625716/129332208-82632163-7eeb-45bf-b852-29b2a5e091d2.png)

**Comment by valosnah** [comment]
Må påpeke at disse endringene har gjort ting bedre, men det er fortsatt et ganske høyt antall feilmeldinger, så jeg føler ikke issuet har blitt fullstendig løst.
Dette kan være errorene burde ha blitt logget som noe annet?

![image](https://user-images.githubusercontent.com/8625716/130419026-7c60ee2d-3da4-4a48-aa9c-ecce4edf0fe0.png)

**Comment by valosnah** [comment]
Da er vi nede på svært lavt antall. Disse skyldes issues med inputen, og må følges opp med dataeier. Kan også hende noe kan bli nedgradert til "warning", lager eget issue på dette.

**Comment by shenluna** [comment]
Se kommentar fra valosnah, lukker dermed saken
