### ISSUE TITLE
Erstatt jsonschema parsing med bruk av jsonschematordf

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-model-publisher#55]
- [ ] mapper.py -> jsonschematordf
- [ ] skrive tester for oppretting av InformationModel (https://github.com/Informasjonsforvaltning/fdk-model-publisher/pull/58#pullrequestreview-775909405)
- [ ] oppdater integrasjonstester for hele systemet

**Comment by valosnah** [comment]
Arkivert tjeneste, lukker issue
