### ISSUE TITLE
Feil contentType: api.cristin.no

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#76]
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.cristin.no/') : Wrong content type for https://api.cristin.no/:0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.cristin.no/')

JSON forventes, får text/html
Må rettes av dataeier

**Comment by stigbd** [comment]
Dette er også eit døme på at vi har for strenge forventningar til innhold i "Endepunktsbeskrivelse". I dette tilfellet får vi tilbake gyldig innhald, men som ikkje er ein openAPI-spesifikasjon. Dette er OK, og fdk-model-publisher bør ignorere denne.

Eg meiner derfor 4ab4028 løyser denne også.
