### ISSUE TITLE
Feil contentType: https://kot.nhn.no/webservice/

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#78]
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=iso-8859-1', url=URL('https://kot.nhn.no/webservice/') : Wrong content type for https://kot.nhn.no/webservice:0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=iso-8859-1', url=URL('https://kot.nhn.no/webservice/')

JSON forventes, får text/html
Må rettes av dataeier

**Comment by stigbd** [comment]
@tenstad Kan du ta ein kik på problemstillinga, ver så snill? Viss du ser ein fiks, assign den gjerne til deg.
