### ISSUE TITLE
Feil contentType: https://data.ssb.no/api/klass/v1/api-guide.html

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#80]
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://data.ssb.no/api/klass/v1/api-guide.html') : Wrong content type for https://data.ssb.no/api/klass/v1/api-guide.html:0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://data.ssb.no/api/klass/v1/api-guide.html')

JSON forventes, får text/html
Må rettes av dataeier

**Comment by shenluna** [comment]
https://github.com/Informasjonsforvaltning/fdk-model-publisher/issues/67

**Comment by stigbd** [comment]
Dette er også eit døme på at vi har for strenge forventningar til innhold i "Endepunktsbeskrivelse". I dette tilfellet får vi tilbake gyldig innhald, men som ikkje er ein openAPI-spesifikasjon. Dette er OK, og fdk-model-publisher bør ignorere denne.

Eg meiner derfor https://github.com/Informasjonsforvaltning/fdk-model-publisher/commit/4ab4028801b53a1927dcc0ce36e8bc5ba84c4fce løyser denne også.
