### ISSUE TITLE
http 404: https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalogue/master/src/main/resources/specification/organization-catalogue.yaml

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#83]
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalogue/master/src/main/resources/specification/organization-catalogue.yaml') : Error connecting to https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalogue/master/src/main/resources/specification/organization-catalogue.yaml:404, message='Not Found', url=URL('https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalogue/master/src/main/resources/specification/organization-catalogue.yaml')

Sannsynligvis relatert til https://github.com/Informasjonsforvaltning/organization-catalog/issues/118

**Comment by stigbd** [comment]
Gjelder antagelegvis følgande API-beskrivelse:
https://data.norge.no/dataservices/16efa1c0-679f-314b-940e-97c1902b7fe5

**Comment by stigbd** [comment]
I så fall skal korrekt lenke vere som følger:
https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalog/main/src/main/resources/specification/organization-catalog.yaml

**Comment by stigbd** [comment]
Løst av fix i dataservice-publiser-etl
