### ISSUE TITLE
http 401: https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#84]
aiohttp.client_exceptions.ClientResponseError: 401, message='', url=URL('https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis') : Error connecting to https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis:401, message='', url=URL('https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis')

Gammel/feil url?

**Comment by stigbd** [comment]
Har tatt kontakt med utgiver som skal oppdatere både api- og datasett-beskrivelsen.

**Comment by stigbd** [comment]
Gjelder følgande datatjeneste: https://data.norge.no/dataservices/835462c8-bdb7-3edf-89c8-1cfd27cee56c
