### ISSUE TITLE
Timeout-error: Timed out connecting to https://data.regjeringen.no/swagger/docs/v1

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#86]
Feil url? Feil på ekstern konfig?
Curl timer ut på 1 minutt og gir SSL_ERROR_SYSCALL

> Traceback (most recent call last):
  File "/app/src/fdk_model_publisher/service/fetcher.py", line 46, in fetch
    async with session.get(urls[0]) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
: Timed out connecting to https://data.regjeringen.no/swagger/docs/v1

**Comment by tenstad** [comment]
Fint å se at https://github.com/Informasjonsforvaltning/fdk-model-publisher/pull/85 funker :smiley_cat:

**Comment by valosnah** [comment]
Gjelder også:
https://api.swaggerhub.com/apis/Skatteetaten_Deling/skattepliktig-api/1.0.0
https://api.swaggerhub.com/apis/Skatteetaten_Deling/tilleggsskatt-api/1.0.0
https://api.swaggerhub.com/apis/Skatteetaten_Deling/omregistreringsavgift-api/1.0.0
https://api.swaggerhub.com/apis/Skatteetaten_Deling/summert-skattegrunnlag-api/1.0.0

**Comment by valosnah** [comment]
Denne timer fortsatt ut.
Curl timer ut mye raskere nå (~10 sek), og gir:
> * Failed to connect to data.regjeringen.no port 443: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to data.regjeringen.no port 443: Connection refused

Prøver man http får man 301->https

**Comment by pooriamehregan** [comment]
@KjerstiSteien Ser ut som denne er fortsatt pågående. 
https://fdk-project.slack.com/archives/C03DTS92RBQ/p1684411240016089

**Comment by KjerstiSteien** [comment]
@pooriamehregan Noe vi burde ta tak i raskt?

**Comment by pooriamehregan** [comment]
Tror @valosnah er bedre kvalifisert til å svare på dette spørsmålet. Men tipper at dette ikke er noe kritisk. Tenkte bare å kommentere det som en påminnelse her da jeg var vaktmester forrige uke. Feilen skjedde igjen onsdag eller tirsdag forrige uke. Men så fort at Hans Olav hadde allerede oprettet et issuet på det i fjor. Så koblet issuet til feilen.

**Comment by KjerstiSteien** [comment]
Aha. Jeg setter den til planning.

**Comment by valosnah** [comment]
Arkivert tjeneste, lukker issue
